services:
  app:
    build: .
    container_name: python-server
    command: run.py
    ports:
      - 8001:8001
    volumes:
      - .:/code
    depends_on:
      - redis
  
  redis:
    image: redis:alpine
